export const PERMISSIONS = {
  USERS: {
    READ_LIST_USERS: "Read List Users",
    READ_DETAIL_USERS: "Read Detail Users",
    CREATE_USERS: "Create Users",
    DELETE_USERS: "Delete Users",
    UPDATE_USERS: "Update Users",
    ACTIVATE_USERS: "Activate Users",
  },
  ROLES: {
    READ_LIST_ROLES: "Read List Roles",
    READ_DETAIL_ROLES: "Read Detail Roles",
    CREATE_ROLES: "Create Roles",
    DELETE_ROLES: "Delete Roles",
    UPDATE_ROLES: "Update Roles",
  },
  PERMISSIONS: {
    READ_LIST_PERMISSIONS: "Read List Permissions",
    READ_DETAIL_PERMISSIONS: "Read Detail Permissions",
    CREATE_PERMISSIONS: "Create Permissions",
    DELETE_PERMISSIONS: "Delete Permissions",
    UPDATE_PERMISSIONS: "Update Permissions",
  },
  SESSIONS: {
    READ_LIST_SESSIONS: "Read List Sessions",
    READ_DETAIL_SESSIONS: "Read Detail Sessions",
    CREATE_SESSIONS: "Create Sessions",
    UPDATE_SESSIONS: "Update Sessions",
    DELETE_SESSIONS: "Delete Sessions",
  },
  TESTS: {
    READ_LIST_TESTS: "Read List Tests",
    READ_DETAIL_TESTS: "Read Detail Tests",
    CREATE_TESTS: "Create Tests",
    UPDATE_TESTS: "Update Tests",
    DELETE_TESTS: "Delete Tests",
  },
  ANSWERS: {
    READ_LIST_ANSWERS: "Read List Answers",
    READ_DETAIL_ANSWERS: "Read Detail Answers",
    CREATE_ANSWERS: "Create Answers",
    UPDATE_ANSWERS: "Update Answers",
    DELETE_ANSWERS: "Delete Answers",
  },
  OPTIONS: {
    READ_LIST_OPTIONS: "Read List Options",
    READ_DETAIL_OPTIONS: "Read Detail Options",
    CREATE_OPTIONS: "Create Options",
    UPDATE_OPTIONS: "Update Options",
    DELETE_OPTIONS: "Delete Options",
  },
  QUESTIONS: {
    READ_LIST_QUESTIONS: "Read List Questions",
    READ_DETAIL_QUESTIONS: "Read Detail Questions",
    CREATE_QUESTIONS: "Create Questions",
    UPDATE_QUESTIONS: "Update Questions",
    DELETE_QUESTIONS: "Delete Questions",
  },
};
