export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot",
    NEW_PASSWORD: "/auth/new-password",
    REFRESH_TOKEN: "/auth/refresh",
    SEND_OTP: "/auth/send-otp",
    VERIFY_EMAIL: "/auth/verify-email",
    CHANGE_PASSWORD: "/users/change-password",
  },
  USERS: {
    LIST: "/users",
    DETAIL: "/users/detail/:id",
    ME: "/users/me",
    CREATE: "/users/create",
    UPDATE: "/users/update/:id",
    UPDATE_ME: "/users/update/me",
    DELETE: "/users/delete/:id",
    ACTIVATE: "/users/activate/:id",
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: "/roles/detail/:id",
    CREATE: "/roles/create",
    UPDATE: "/roles/update/:id",
    DELETE: "/roles/delete/:id",
  },
  PERMISSIONS: {
    LIST: "/permissions",
    DETAIL: "/permissions/detail/:id",
    CREATE: "/permissions/create",
    UPDATE: "/permissions/update/:id",
    DELETE: "/permissions/delete/:id",
  },
  OPTIONS: {
    LIST: "/options",
    DETAIL: "/options/detail/:id",
    CREATE: "/options/create",
    UPDATE: "/options/update/:id",
    DELETE: "/options/delete/:id",
  },
  QUESTIONS: {
    LIST: "/questions",
    DETAIL: "/questions/detail/:id",
    CREATE: "/questions/create",
    UPDATE: "/questions/update/:id",
    DELETE: "/questions/delete/:id",
  },
  ANSWERS: {
    CREATE_AKADEMIK: "/answers/create-akademik",
    CREATE_PSIKOLOGI: "/answers/create-psikologi",
    DETAIL: "/answers/detail/:id",
    DETAIL_TEST_AND_USER_ID: "/answers/detail/:testId/:userId",
    DETAIL_TEST_SUB_TEST_AND_USER_ID: "/answers/detail/:testId/:subTestId/:userId",
    DELETE: "/answers/delete/:id",
  },
  TESTS: {
    LIST: "/tests",
    DETAIL: "/tests/detail/:id",
    CREATE: "/tests/create",
    UPDATE: "/tests/update/:id",
    DELETE: "/tests/delete/:id",
  },
  SESSIONS: {
    LIST: "/sessions",
    DETAIL: "/sessions/detail/:id",
    CREATE: "/sessions/create",
    UPDATE: "/sessions/update/:id",
    DELETE: "/sessions/delete/:id",
  },
  FLAGS: {
    LIST: "/flags",
    DETAIL: "/flags/detail/:id",
    CREATE: "/flags/create",
    UPDATE: "/flags/update/:id",
    DELETE: "/flags/delete/:id",
  },
  RESULTS: {
    LIST: "/results",
    DETAIL: "/results/detail/:id",
    CREATE: "/results/create",
    UPDATE: "/results/update/:id",
    DELETE: "/results/delete/:id",
  },
  ACCURATIONS: {
    LIST: "/accurations",
    DETAIL: "/accurations/detail/:id",
    CREATE: "/accurations/create",
    UPDATE: "/accurations/update/:id",
    DELETE: "/accurations/delete/:id",
  },
  PAYMENTS: {
    LIST: "/payments",
    DETAIL: "/payments/detail/:id",
    CREATE: "/payments/create",
    UPDATE: "/payments/update/:id",
    DELETE: "/payments/delete/:id",
  },
  STORAGE: {
    UPLOAD: "/storage/upload",
  },
};
