import { env } from "../env";

export const FEATURE_FLAGS = {
  DASHBOARD: {
    READ_DASHBOARD: env.VITE_FEATURE_FLAG_DASHBOARD_READ_DASHBOARD,
  },
  IAM: {
    USERS: {
      LIST_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_LIST,
      DETAIL_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_DETAIL,
      CREATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_CREATE,
      UPDATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_UPDATE,
      DELETE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_DELETE,
      ACTIVATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_ACTIVATE,
    },
    PERMISSIONS: {
      LIST_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_LIST,
      DETAIL_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_DETAIL,
      CREATE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_CREATE,
      UPDATE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_UPDATE,
      DELETE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_DELETE,
    },
    ROLES: {
      LIST_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_LIST,
      DETAIL_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_DETAIL,
      CREATE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_CREATE,
      UPDATE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_UPDATE,
      DELETE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_DELETE,
    },
  },
  EXAMS: {
    SESSIONS: {
      LIST_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_LIST,
      DETAIL_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_DETAIL,
      CREATE_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_CREATE,
      UPDATE_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_UPDATE,
    },
    TESTS: {
      LIST_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_LIST,
      DETAIL_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_DETAIL,
      CREATE_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_CREATE,
      UPDATE_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_UPDATE,
    },
    ACCURATIONS: {
      LIST_ACCURATIONS: env.VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_LIST,
      DETAIL_ACCURATIONS: env.VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_DETAIL,
      CREATE_ACCURATIONS: env.VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_CREATE,
      UPDATE_ACCURATIONS: env.VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_UPDATE,
    },
    RESULTS: {
      LIST_RESULTS: env.VITE_FEATURE_FLAG_EXAMS_RESULTS_LIST,
      DETAIL_RESULTS: env.VITE_FEATURE_FLAG_EXAMS_RESULTS_DETAIL,
      CREATE_RESULTS: env.VITE_FEATURE_FLAG_EXAMS_RESULTS_CREATE,
      UPDATE_RESULTS: env.VITE_FEATURE_FLAG_EXAMS_RESULTS_UPDATE,
    },
    QUESTIONS: {
      LIST_QUESTIONS: env.VITE_FEATURE_FLAG_EXAMS_QUESTIONS_LIST,
      DETAIL_QUESTIONS: env.VITE_FEATURE_FLAG_EXAMS_QUESTIONS_DETAIL,
      CREATE_QUESTIONS: env.VITE_FEATURE_FLAG_EXAMS_QUESTIONS_CREATE,
      UPDATE_QUESTIONS: env.VITE_FEATURE_FLAG_EXAMS_QUESTIONS_UPDATE,
      DELETE_QUESTIONS: env.VITE_FEATURE_FLAG_EXAMS_QUESTIONS_DELETE,
    },
  },
  PAYMENTS: {
    LIST_PAYMENTS: env.VITE_FEATURE_FLAG_PAYMENTS_LIST,
    DETAIL_PAYMENTS: env.VITE_FEATURE_FLAG_PAYMENTS_DETAIL,
    CREATE_PAYMENTS: env.VITE_FEATURE_FLAG_PAYMENTS_CREATE,
    UPDATE_PAYMENTS: env.VITE_FEATURE_FLAG_PAYMENTS_UPDATE,
    DELETE_PAYMENTS: env.VITE_FEATURE_FLAG_PAYMENTS_DELETE,
  },
  FLAGS: {
    LIST_FLAGS: env.VITE_FEATURE_FLAG_FLAGS_LIST,
    DETAIL_FLAGS: env.VITE_FEATURE_FLAG_FLAGS_DETAIL,
    CREATE_FLAGS: env.VITE_FEATURE_FLAG_FLAGS_CREATE,
    UPDATE_FLAGS: env.VITE_FEATURE_FLAG_FLAGS_UPDATE,
    DELETE_FLAGS: env.VITE_FEATURE_FLAG_FLAGS_DELETE,
  },
};
