import { env } from "../env";

export const FEATURE_FLAGS = {
  IAM: {
    USERS: {
      LIST_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_LIST,
      DETAIL_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_DETAIL,
      CREATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_CREATE,
      UPDATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_UPDATE,
      DELETE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_DELETE,
      ACTIVATE_USERS: env.VITE_FEATURE_FLAG_IAM_USERS_ACTIVATE,
    },
    PERMISSIONS: {
      LIST_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_LIST,
      DETAIL_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_DETAIL,
      CREATE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_CREATE,
      UPDATE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_UPDATE,
      DELETE_PERMISSIONS: env.VITE_FEATURE_FLAG_IAM_PERMISSIONS_DELETE,
    },
    ROLES: {
      LIST_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_LIST,
      DETAIL_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_DETAIL,
      CREATE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_CREATE,
      UPDATE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_UPDATE,
      DELETE_ROLES: env.VITE_FEATURE_FLAG_IAM_ROLES_DELETE,
    },
  },
  EXAMS: {
    SESSIONS: {
      LIST_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_LIST,
      DETAIL_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_DETAIL,
      CREATE_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_CREATE,
      UPDATE_SESSIONS: env.VITE_FEATURE_FLAG_EXAMS_SESSIONS_UPDATE,
    },
    TESTS: {
      LIST_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_LIST,
      DETAIL_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_DETAIL,
      CREATE_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_CREATE,
      UPDATE_TESTS: env.VITE_FEATURE_FLAG_EXAMS_TESTS_UPDATE,
    },
  },
};
