import { z } from "zod";

const zEnvBool = () =>
  z.union([z.literal("true"), z.literal("false")]).transform((val) => val === "true");

const envSchema = z.object({
  VITE_API_BASE_URL: z.string().url(),
  VITE_BASE_URL: z.string().url(),

  VITE_FEATURE_FLAG_IAM_USERS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_USERS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_USERS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_USERS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_USERS_DELETE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_USERS_ACTIVATE: zEnvBool(),

  VITE_FEATURE_FLAG_IAM_PERMISSIONS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_PERMISSIONS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_PERMISSIONS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_PERMISSIONS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_PERMISSIONS_DELETE: zEnvBool(),

  VITE_FEATURE_FLAG_IAM_ROLES_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_ROLES_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_ROLES_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_ROLES_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_IAM_ROLES_DELETE: zEnvBool(),

  VITE_FEATURE_FLAG_EXAMS_SESSIONS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_SESSIONS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_SESSIONS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_SESSIONS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_SESSIONS_DELETE: zEnvBool(),

  VITE_FEATURE_FLAG_EXAMS_TESTS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_TESTS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_TESTS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_TESTS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_TESTS_DELETE: zEnvBool(),

  VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_ACCURATIONS_DELETE: zEnvBool(),

  VITE_FEATURE_FLAG_EXAMS_RESULTS_LIST: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_RESULTS_DETAIL: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_RESULTS_CREATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_RESULTS_UPDATE: zEnvBool(),
  VITE_FEATURE_FLAG_EXAMS_RESULTS_DELETE: zEnvBool(),
});

export const env = envSchema.parse(import.meta.env);
